---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
    #helm.sh/hook-weight: "-5"
  name: preinstall-{{ $.Values.cluster.name }}-add-pull-secret-job
  namespace: {{ $.Values.gitops.namespace }}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: {{ $.Values.gitops.service_account }}
      serviceAccountName: {{ $.Values.gitops.service_account_name }}
      terminationGracePeriodSeconds: 30
      containers:
        - image: lab-registry.ocpmgmt.lab.diktio.net/nsatsia/ose-tools-rhel8
          imagePullPolicy: IfNotPresent
          name: {{ $.Values.cluster.name }}-add-pull-secret-job
          command:
            - /bin/bash
            - -c
            - |
              echo "Adding local pull secret to the global one."
              cd /tmp
              oc extract secret/pull-secret -n openshift-config --confirm
              cat .dockerconfigjson | \
                  jq --compact-output '.auths["{{ $.Values.ai.registry_url }}/{{ $.Values.ai.registry_user }}"] |= . + {"auth":"{{ printf "%s:%s" $.Values.ai.registry_user $.Values.ai.registry_password | b64enc  }}"}' \
                  > new_dockerconfigjson
              oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=new_dockerconfigjson
              rm -f .dockerconfigjson new_dockerconfigjson
              echo "All done! Hooray!"

